#!/usr/bin/env python3
"""Generate thin Hermes instruction adapters. Dry-run unless --apply is given.

Only the seven existing SOUL.md files are changed. Runtime configuration,
credentials, memories and installed skills are outside this adapter's scope.
"""
from __future__ import annotations

import argparse
from contextlib import contextmanager
from datetime import datetime, timezone
import hashlib
import json
import os
from pathlib import Path
import stat
import sys
import tempfile

ROLES = ("desk", "pa", "reader", "maker", "checker", "flags")
TARGETS = ("SOUL.md",) + tuple(f"profiles/rua-{role}/SOUL.md" for role in ROLES)
SOURCES = ("AGENTS.md", "00-system/communication.md", "00-system/working-roles.md")
MAX_FILE = 1024 * 1024


def digest(data):
    return hashlib.sha256(data).hexdigest()


def checked_path(value):
    """Reject symlinks before canonicalizing, including symlink ancestors."""
    path = Path(os.path.abspath(os.path.expanduser(str(value))))
    for item in (path, *path.parents):
        if item.is_symlink():
            raise ValueError(f"Symlink path refused: {item}")
    return path


def outside_git(path, repo):
    path = checked_path(path)
    if path == repo or repo in path.parents:
        raise ValueError("Private backups must be outside the repository")
    for ancestor in (path, *path.parents):
        if (ancestor / ".git").exists() or ancestor.name == ".git":
            raise ValueError("Private backups must be outside all Git worktrees")
        if (ancestor / "HEAD").is_file() and (ancestor / "objects").is_dir() and (ancestor / "refs").is_dir():
            raise ValueError("Private backups must be outside bare Git repositories")
    return path


def read_file(path, private=False):
    path = checked_path(path)
    fd = os.open(path, os.O_RDONLY | os.O_NOFOLLOW)
    with os.fdopen(fd, "rb") as stream:
        info = os.fstat(stream.fileno())
        if not stat.S_ISREG(info.st_mode) or info.st_size > MAX_FILE:
            raise ValueError(f"Expected a regular file no larger than 1 MiB: {path}")
        if private and (info.st_uid != os.getuid() or stat.S_IMODE(info.st_mode) & 0o077):
            raise ValueError(f"Backup file must be owner-only: {path}")
        return stream.read(MAX_FILE + 1), stat.S_IMODE(info.st_mode)


def check_private_dir(path):
    path = checked_path(path)
    info = path.stat()
    if not stat.S_ISDIR(info.st_mode) or info.st_uid != os.getuid() or stat.S_IMODE(info.st_mode) & 0o077:
        raise ValueError(f"Backup directory must be owned by this user and owner-only: {path}")


def generated(repo, role):
    source_lines = "\n".join(f"- {repo / source}" for source in SOURCES)
    coordinator = role is None
    identity = "the active coordinator, fulfilling the `desk` role" if coordinator else f"the `{role}` role"
    ending = ("Own completion of the request and compose one final answer from returned findings. "
              "Do not paste worker stdout or internal tool transcripts as the reply. Preserve material "
              "uncertainty and cite useful sources.") if coordinator else (
              "Return the requested result to the caller with sources, completion evidence and any "
              "material blocker. Stay within the assigned ownership; the caller coordinates the final answer.")
    return f"""# Rua instruction adapter

Generated by 30-tools/rua-seat/sync_profiles.py. Shared policy is maintained in
the repository. Regenerate this adapter when its repository path changes.

You are {identity}. Read these shared instructions before work:
{source_lines}

Your responsibilities come from the canonical role table in working-roles.md.
Load only the job's relevant doctrine. Carry the user's scope, decisions and
authorization through the task. User instructions take precedence over skills.

Discover tools and installed skills in the current runtime when needed. Read a
relevant connector skill before using it. Existing runtime skills and connection
configuration remain the source for access mechanics; verify availability before
claiming access or failure. Use connected Workspace tools for current mail,
calendar and Drive facts, and the repository vault interface for client records.
Do not treat an old session or this adapter as proof of current access.

Delegate through available collaboration tools or rua-seat when useful. Consult
{repo / '30-tools/rua-seat/README.md'} for runner mechanics.
{ending}
""".encode()


def snapshot(home):
    values = {}
    for name in TARGETS:
        values[name] = read_file(home / name)
    return values


def atomic_write(path, data, mode):
    checked_path(path)
    fd, temp = tempfile.mkstemp(prefix=".rua-soul-", dir=path.parent)
    try:
        with os.fdopen(fd, "wb") as stream:
            os.fchmod(stream.fileno(), mode)
            stream.write(data)
            stream.flush()
            os.fsync(stream.fileno())
        checked_path(path)
        os.replace(temp, path)
    finally:
        if os.path.exists(temp):
            os.unlink(temp)


@contextmanager
def lock(home):
    path = checked_path(home / ".rua-soul-sync.lock")
    try:
        path.mkdir(mode=0o700)
    except FileExistsError as exc:
        raise ValueError("Another profile sync may be running; inspect .rua-soul-sync.lock before retrying") from exc
    try:
        yield
    finally:
        path.rmdir()


def backup(home, repo, old, new):
    parent = outside_git(home / ".rua-soul-backups", repo)
    parent.mkdir(mode=0o700, exist_ok=True)
    check_private_dir(parent)
    stamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%S.%fZ-")
    folder = Path(tempfile.mkdtemp(prefix=stamp, dir=parent))
    entries = []
    for index, name in enumerate(TARGETS):
        data, mode = old[name]
        filename = f"{index}.soul"
        atomic_write(folder / filename, data, 0o600)
        entries.append({"target": name, "file": filename, "sha256": digest(data),
                        "mode": mode, "generated_sha256": digest(new[name][0])})
    manifest = {"version": 1, "repo": str(repo), "hermes_home": str(home), "entries": entries}
    atomic_write(folder / "manifest.json", (json.dumps(manifest, indent=2) + "\n").encode(), 0o600)
    return folder


def replace_set(home, old, new):
    """Rollback changed targets on failure; retain durable backup for crash recovery."""
    touched = []
    try:
        for name in TARGETS:
            if old[name] == new[name]:
                continue
            path = home / name
            if read_file(path) != old[name]:
                raise ValueError(f"Target changed during sync: {name}")
            # Include the target before replacement so an interrupt immediately
            # after os.replace also participates in recovery.
            touched.append(name)
            atomic_write(path, *new[name])
    except BaseException as exc:
        failures = []
        for name in reversed(touched):
            try:
                current = read_file(home / name)
                if current == old[name]:
                    continue
                if current != new[name]:
                    raise ValueError("target changed externally")
                atomic_write(home / name, *old[name])
            except BaseException:
                failures.append(name)
        if failures:
            raise RuntimeError("Partial failure; restore from the retained backup after inspecting: " + ", ".join(failures)) from exc
        raise


def restore_plan(folder, home, repo, current):
    folder = outside_git(folder, repo)
    check_private_dir(folder)
    raw, _ = read_file(folder / "manifest.json", private=True)
    manifest = json.loads(raw)
    if not isinstance(manifest, dict) or manifest.get("version") != 1:
        raise ValueError("Invalid backup manifest version")
    if manifest.get("repo") != str(repo) or manifest.get("hermes_home") != str(home):
        raise ValueError("Backup belongs to a different repository or Hermes home")
    entries = manifest.get("entries")
    if not isinstance(entries, list) or len(entries) != len(TARGETS):
        raise ValueError("Backup must contain exactly the seven known targets")
    planned = {}
    for index, name in enumerate(TARGETS):
        entry = entries[index]
        if not isinstance(entry, dict) or entry.get("target") != name or entry.get("file") != f"{index}.soul":
            raise ValueError("Unexpected backup target or filename")
        data, _ = read_file(folder / entry["file"], private=True)
        mode = entry.get("mode")
        if type(mode) is not int or mode < 0 or mode > 0o777:
            raise ValueError("Invalid original file permissions")
        if digest(data) != entry.get("sha256"):
            raise ValueError("Backup content does not match its manifest")
        if digest(current[name][0]) not in (entry["sha256"], entry.get("generated_sha256")):
            raise ValueError(f"Refusing to overwrite subsequent edits: {name}")
        planned[name] = (data, mode)
    return planned


def run(repo, home, apply=False, restore=None):
    repo, home = checked_path(repo), checked_path(home)
    if not repo.is_dir() or not home.is_dir():
        raise ValueError("Repository and Hermes home must be existing directories")
    for source in SOURCES:
        read_file(repo / source)
    read_file(repo / "30-tools/rua-seat/README.md")
    # Validate even in dry runs: private backups must never enter Git.
    outside_git(home / ".rua-soul-backups", repo)

    def prepare():
        old = snapshot(home)
        new = restore_plan(restore, home, repo, old) if restore else {
            name: (generated(repo, None if index == 0 else ROLES[index - 1]), 0o600)
            for index, name in enumerate(TARGETS)
        }
        return old, new

    if not apply:
        old, new = prepare()
        changed = [name for name in TARGETS if old[name] != new[name]]
        return {"mode": "dry-run", "operation": "restore" if restore else "sync", "changed": changed}
    with lock(home):
        old, new = prepare()
        changed = [name for name in TARGETS if old[name] != new[name]]
        if not changed:
            return {"mode": "applied", "operation": "restore" if restore else "sync", "changed": []}
        # Restores also preserve the pre-restore state, making recovery reversible.
        saved = backup(home, repo, old, new)
        try:
            replace_set(home, old, new)
        except BaseException as exc:
            raise RuntimeError(f"Profile update failed; recovery backup: {saved}. {exc}") from exc
        return {"mode": "applied", "operation": "restore" if restore else "sync", "changed": changed, "backup": str(saved)}


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo", type=Path, required=True)
    parser.add_argument("--hermes-home", type=Path, required=True)
    parser.add_argument("--apply", action="store_true", help="back up and replace SOUL files (default: report drift only)")
    parser.add_argument("--restore", type=Path, metavar="BACKUP", help="restore a validated backup; requires --apply to write")
    args = parser.parse_args(argv)
    try:
        print(json.dumps(run(args.repo, args.hermes_home, args.apply, args.restore), indent=2))
        return 0
    except (OSError, ValueError, RuntimeError) as exc:
        print(f"Profile sync refused or failed: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
